name: CI/CD for Order Service

on:
  push:
    paths:
      - 'services/order-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    # Step 3: Restore dependencies
    - name: Restore dependencies
      run: dotnet restore services/order-service

    # Step 4: Build the service
    - name: Build
      run: dotnet build services/order-service --no-restore

    # Step 5: Run tests
    - name: Run tests
      run: dotnet test services/order-service --no-build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    # Deployment placeholder step
    - name: Deploy
      run: echo "Deploying Order Service..."
