version: '3.8'

services:
  storefront:
    build: ./frontend/storefront
    ports:
      - "3000:3000"
  backoffice:
    build: ./frontend/backoffice
    ports:
      - "4200:4200"
  customer-service:
    build: ./services/product-service
    ports:
      - "5001:5001"
  identity-service:
    build: ./services/product-service
    ports:
      - "5002:5002"
  inventory-service:
    build: ./services/product-service
    ports:
      - "5003:5003"
  order-service:
    build: ./services/order-service
    ports:
      - "5004:5004"
  product-service:
    build: ./services/product-service
    ports:
      - "5005:5005"
  user-service:
    build: ./services/product-service
    ports:
      - "5006:5006"